version: '2'
services:

  flask:
    restart: always
    build:
        context: ./docker/
    volumes:
      - ./app:/app
    ports:
      - "4430:80"
    links:
      - mysql
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: flask run --host=0.0.0.0 --port=80
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"
  
  mysql:
    restart: always
    image: mysql:5.7
    environment:
      TZ: "America/Toronto"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "SomeStrongPassword123!"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
