FROM tiangolo/uwsgi-nginx-flask:python3.6

# RUN pip install mysql-connector
RUN pip install mysqlclient
RUN pip install flask-mysql
RUN pip install simplejson
RUN pip install connexion
RUN pip install connexion[swagger-ui]
RUN pip install Flask-SQLAlchemy flask-marshmallow marshmallow-sqlalchemy marshmallow
RUN pip install pytz

